const STORE_KEY='pjStoreProducts_v1';const starterProducts=[
{id:'p1',name:'Everyday Statement Tote',category:'Accessories',price:349,description:'A roomy everyday carryall with a clean, considered silhouette.',badge:'Bestseller',image:'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p2',name:'The Weekend Essential',category:'Style',price:599,description:'An easy layer for slow mornings and spontaneous plans.',badge:'The edit',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p3',name:'Sculpted Ceramic Vase',category:'Living',price:279,description:'A tactile accent that brings quiet character to any corner.',badge:'New',image:'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p4',name:'Minimal Everyday Watch',category:'Accessories',price:799,description:'A timeless finishing touch with understated detailing.',badge:'Limited edit',image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p5',name:'Soft Form Shoulder Bag',category:'Style',price:489,description:'A versatile silhouette made to move effortlessly through the day.',badge:'Popular',image:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p6',name:'The Desk Upgrade',category:'Tech',price:429,description:'A neat little upgrade for your everyday work setup.',badge:'Everyday pick',image:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p7',name:'Warm Light Table Lamp',category:'Living',price:549,description:'Soft ambient light for slower evenings and calmer spaces.',badge:'The home edit',image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p8',name:'Daily Carry Crossbody',category:'Accessories',price:389,description:'Keep the essentials close with a compact, hands-free favourite.',badge:'Bestseller',image:'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=82',active:true}];
const $=id=>document.getElementById(id);const money=n=>'R'+Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2});const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));let products=load(),pendingImage='';function load(){try{const p=JSON.parse(localStorage.getItem(STORE_KEY));return Array.isArray(p)&&p.length?p:starterProducts.map(p=>({...p}))}catch{return starterProducts.map(p=>({...p}))}}function persist(){try{localStorage.setItem(STORE_KEY,JSON.stringify(products));return true}catch(e){notice('Could not save. The browser storage may be full; try a smaller image.');return false}}function notice(s){const t=$('toast');t.textContent=s;t.classList.add('show');clearTimeout(window._pjToast);window._pjToast=setTimeout(()=>t.classList.remove('show'),2600)}
function render(){const q=$('admin-search').value.toLowerCase();const list=products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(q));$('product-total').textContent=products.length+' products · '+products.filter(p=>p.active!==false).length+' visible';$('admin-list').innerHTML=list.length?list.map(p=>'<article class="admin-product"><img src="'+esc(p.image)+'" alt=""><div><h3>'+esc(p.name)+'</h3><p>'+esc(p.category)+' · '+money(p.price)+' · '+(p.active===false?'Hidden':'Visible')+'</p></div><div class="admin-product-actions"><button class="small-button" data-edit="'+esc(p.id)+'">Edit</button><button class="small-button" data-toggle="'+esc(p.id)+'">'+(p.active===false?'Show':'Hide')+'</button><button class="small-button danger" data-delete="'+esc(p.id)+'">Delete</button></div></article>').join(''):'<div class="empty-admin">No products match that search.</div>'}
function openModal(p){$('product-form').reset();pendingImage='';$('image-preview').classList.add('hidden');$('product-id').value=p?.id||'';$('modal-title').textContent=p?'Edit product':'Add a product';$('product-name').value=p?.name||'';$('product-price').value=p?.price??'';$('product-category').value=p?.category||'Accessories';$('product-description').value=p?.description||'';$('product-image-url').value=p?.image&&!p.image.startsWith('data:')?p.image:'';$('product-badge').value=p?.badge||'';$('product-active').value=String(p?.active!==false);if(p?.image){$('image-preview').src=p.image;$('image-preview').classList.remove('hidden')} $('product-modal').classList.remove('hidden');$('product-name').focus()}
function closeModal(){$('product-modal').classList.add('hidden');pendingImage=''}
$('add-product').addEventListener('click',()=>openModal());$('modal-close').addEventListener('click',closeModal);$('cancel-product').addEventListener('click',closeModal);$('product-modal').addEventListener('click',e=>{if(e.target===$('product-modal'))closeModal()});$('admin-search').addEventListener('input',render);
$('product-image-file').addEventListener('change',e=>{const file=e.target.files?.[0];if(!file)return;if(!file.type.startsWith('image/')){notice('Please choose an image file.');return}if(file.size>1.5*1024*1024){notice('Please use an image under 1.5 MB for browser storage.');e.target.value='';return}const reader=new FileReader();reader.onload=()=>{pendingImage=reader.result;$('image-preview').src=pendingImage;$('image-preview').classList.remove('hidden')};reader.readAsDataURL(file)});
$('product-form').addEventListener('submit',e=>{e.preventDefault();const id=$('product-id').value||'p'+Date.now().toString(36);const existing=products.find(p=>p.id===id);const image=pendingImage||$('product-image-url').value.trim()||existing?.image||'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=900&q=80';const p={id,name:$('product-name').value.trim(),price:Number($('product-price').value),category:$('product-category').value,description:$('product-description').value.trim(),image,badge:$('product-badge').value.trim(),active:$('product-active').value==='true'};if(!p.name||!Number.isFinite(p.price)||p.price<0){notice('Add a product name and valid price.');return}const previous=products;products=existing?products.map(x=>x.id===id?p:x):[p,...products];if(!persist()){products=previous;return}closeModal();render();notice('Product saved')});
$('admin-list').addEventListener('click',e=>{const edit=e.target.closest('[data-edit]');if(edit){openModal(products.find(p=>p.id===edit.dataset.edit));return}const toggle=e.target.closest('[data-toggle]');if(toggle){products=products.map(p=>p.id===toggle.dataset.toggle?{...p,active:p.active===false}:p);if(persist()){render();notice('Product visibility updated')}return}const del=e.target.closest('[data-delete]');if(del){const p=products.find(x=>x.id===del.dataset.delete);if(!p||!confirm('Delete “'+p.name+'” from this browser catalogue?'))return;products=products.filter(x=>x.id!==del.dataset.delete);if(persist()){render();notice('Product deleted')}}});
$('save-whatsapp').addEventListener('click',()=>{const num=$('whatsapp-number').value.replace(/\D/g,'');if(num.length<9||num.length>15){$('settings-status').textContent='Enter a valid number with country code.';return}localStorage.setItem('pjStoreWhatsApp',num);$('settings-status').textContent='Saved in this browser.';notice('WhatsApp number saved')});
$('reset-catalogue').addEventListener('click',()=>{if(!confirm('Restore the eight sample products? This replaces your current browser catalogue.'))return;products=starterProducts.map(p=>({...p}));if(persist()){render();notice('Sample catalogue restored')}});
$('whatsapp-number').value=localStorage.getItem('pjStoreWhatsApp')||'';window.addEventListener('storage',e=>{if(e.key===STORE_KEY){products=load();render()}});render();