const STORE_KEY='pjStoreProducts_v1', CART_KEY='pjStoreCart_v1';
const starterProducts=[
{id:'p1',name:'Everyday Statement Tote',category:'Accessories',price:349,description:'A roomy everyday carryall with a clean, considered silhouette.',badge:'Bestseller',image:'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p2',name:'The Weekend Essential',category:'Style',price:599,description:'An easy layer for slow mornings and spontaneous plans.',badge:'The edit',image:'https://images.unsplash.com/photo-1529139574466-a303027c1d8b?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p3',name:'Sculpted Ceramic Vase',category:'Living',price:279,description:'A tactile accent that brings quiet character to any corner.',badge:'New',image:'https://images.unsplash.com/photo-1578500494198-246f612d3b3d?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p4',name:'Minimal Everyday Watch',category:'Accessories',price:799,description:'A timeless finishing touch with understated detailing.',badge:'Limited edit',image:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p5',name:'Soft Form Shoulder Bag',category:'Style',price:489,description:'A versatile silhouette made to move effortlessly through the day.',badge:'Popular',image:'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p6',name:'The Desk Upgrade',category:'Tech',price:429,description:'A neat little upgrade for your everyday work setup.',badge:'Everyday pick',image:'https://images.unsplash.com/photo-1496181133206-80ce9b88a853?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p7',name:'Warm Light Table Lamp',category:'Living',price:549,description:'Soft ambient light for slower evenings and calmer spaces.',badge:'The home edit',image:'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=900&q=82',active:true},
{id:'p8',name:'Daily Carry Crossbody',category:'Accessories',price:389,description:'Keep the essentials close with a compact, hands-free favourite.',badge:'Bestseller',image:'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?auto=format&fit=crop&w=900&q=82',active:true}
];
const money=n=>'R'+Number(n||0).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2});
function loadProducts(){try{const p=JSON.parse(localStorage.getItem(STORE_KEY));return Array.isArray(p)&&p.length?p:starterProducts}catch{return starterProducts}}
let products=loadProducts(),cart=readCart(),category='All',searchTerm='';
function readCart(){try{return JSON.parse(localStorage.getItem(CART_KEY))||{}}catch{return {}}}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(cart));renderCartCount()}
function escapeHTML(s=''){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function visibleProducts(){let list=products.filter(p=>p.active!==false&&(category==='All'||p.category===category)&&((p.name+' '+p.description+' '+p.category).toLowerCase().includes(searchTerm.toLowerCase())));const sort=document.getElementById('sort-select')?.value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);return list}
function renderProducts(){const grid=document.getElementById('product-grid');if(!grid)return;const list=visibleProducts();grid.innerHTML=list.length?list.map(p=>'<article class="product-card"><div class="product-photo"><img loading="lazy" src="'+escapeHTML(p.image)+'" alt="'+escapeHTML(p.name)+'" onerror="this.onerror=null;this.src=\'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=75\'">'+(p.badge?'<span class="product-badge">'+escapeHTML(p.badge)+'</span>':'')+'<button class="quick-add" data-add="'+escapeHTML(p.id)+'">＋ Add to bag</button></div><div class="product-info"><span class="product-category">'+escapeHTML(p.category)+'</span><h3>'+escapeHTML(p.name)+'</h3><div class="product-bottom"><strong class="product-price">'+money(p.price)+'</strong><span class="product-note">Thoughtfully selected</span></div></div></article>').join(''):'<div class="empty-state">No pieces found. Try another search or category.</div>'}
function renderCartCount(){const count=Object.values(cart).reduce((a,n)=>a+Number(n),0);const el=document.getElementById('cart-count'),drawer=document.getElementById('drawer-count');if(el)el.textContent=count;if(drawer)drawer.textContent='('+count+')'}
function renderCart(){const box=document.getElementById('cart-items');if(!box)return;const entries=Object.entries(cart).filter(([id,q])=>q>0&&products.some(p=>p.id===id));let total=0;box.innerHTML=entries.length?entries.map(([id,q])=>{const p=products.find(x=>x.id===id);total+=p.price*q;return '<div class="cart-line"><img src="'+escapeHTML(p.image)+'" alt=""><div><h3>'+escapeHTML(p.name)+'</h3><p>'+money(p.price)+'</p><div class="qty-controls"><button data-qty="'+id+'" data-delta="-1" aria-label="Decrease quantity">−</button><span>'+q+'</span><button data-qty="'+id+'" data-delta="1" aria-label="Increase quantity">＋</button></div></div><button class="remove-item" data-remove="'+id+'" aria-label="Remove item">×</button></div>'}).join(''):'<div class="empty-state">Your bag is taking a little break.<br>Add a piece you love to get started.</div>';document.getElementById('cart-total').textContent=money(total);renderCartCount()}
function openCart(){document.getElementById('cart-drawer').classList.add('open');document.getElementById('cart-drawer').setAttribute('aria-hidden','false');document.getElementById('cart-overlay').classList.remove('hidden');renderCart()}
function closeCart(){document.getElementById('cart-drawer').classList.remove('open');document.getElementById('cart-drawer').setAttribute('aria-hidden','true');document.getElementById('cart-overlay').classList.add('hidden')}
let toastTimer;function toast(s){const el=document.getElementById('toast');el.textContent=s;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2200)}
document.addEventListener('click',e=>{const add=e.target.closest('[data-add]');if(add){const id=add.dataset.add;cart[id]=(cart[id]||0)+1;saveCart();renderCart();toast('Added to your bag');return}const qty=e.target.closest('[data-qty]');if(qty){const id=qty.dataset.qty;cart[id]=Math.max(0,(cart[id]||0)+Number(qty.dataset.delta));if(!cart[id])delete cart[id];saveCart();renderCart();return}const rem=e.target.closest('[data-remove]');if(rem){delete cart[rem.dataset.remove];saveCart();renderCart()}});
document.getElementById('cart-open').addEventListener('click',openCart);document.getElementById('cart-close').addEventListener('click',closeCart);document.getElementById('cart-overlay').addEventListener('click',closeCart);
document.getElementById('checkout-button').addEventListener('click',()=>{const entries=Object.entries(cart).filter(([id,q])=>q>0&&products.some(p=>p.id===id));if(!entries.length){toast('Your bag is empty');return}let total=0;const lines=entries.map(([id,q])=>{const p=products.find(x=>x.id===id);total+=p.price*q;return '• '+p.name+' × '+q+' — '+money(p.price*q)});const message='Hi PJ Store! I would like to enquire about this order:\n\n'+lines.join('\n')+'\n\nSubtotal: '+money(total)+'\n\nPlease confirm availability, delivery and payment details.';const phone=(localStorage.getItem('pjStoreWhatsApp')||'').replace(/\D/g,'');if(!phone){toast('Add your WhatsApp number in Store Studio first');return}window.open('https://wa.me/'+phone+'?text='+encodeURIComponent(message),'_blank','noopener')});
document.getElementById('category-filters').addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;category=b.dataset.category;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x===b));renderProducts()});
document.getElementById('sort-select').addEventListener('change',renderProducts);
document.getElementById('search-toggle').addEventListener('click',()=>{const bar=document.getElementById('search-bar');bar.classList.toggle('hidden');if(!bar.classList.contains('hidden'))document.getElementById('search-input').focus()});
document.getElementById('search-input').addEventListener('input',e=>{searchTerm=e.target.value;renderProducts();if(searchTerm)document.getElementById('shop').scrollIntoView({behavior:'smooth'})});
document.getElementById('menu-toggle').addEventListener('click',()=>{const nav=document.querySelector('.desktop-nav');const opened=nav.style.display==='flex';nav.style.cssText=opened?'':'display:flex;position:absolute;top:70px;left:0;right:0;background:var(--paper);padding:22px 6%;flex-direction:column;gap:22px;border-bottom:1px solid var(--line);z-index:12'});document.getElementById('year').textContent=new Date().getFullYear();
const waLink=document.getElementById('contact-whatsapp');function setContactLink(){const phone=(localStorage.getItem('pjStoreWhatsApp')||'').replace(/\D/g,'');waLink.href=phone?'https://wa.me/'+phone+'?text='+encodeURIComponent('Hi PJ Store! I have a question about your collection.'):'#help';if(!phone)waLink.addEventListener('click',e=>{e.preventDefault();toast('Add your WhatsApp number in Store Studio first')},{once:true})}setContactLink();
window.addEventListener('storage',e=>{if(e.key===STORE_KEY){products=loadProducts();renderProducts()}if(e.key===CART_KEY){cart=readCart();renderCart()}if(e.key==='pjStoreWhatsApp')setContactLink()});
renderProducts();renderCartCount();